version: "3"
services:
  postgres:
    image: postgres:11.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: eventor
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - '5437:5432'
